application: serobocon
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.5"

builtins:

- django_wsgi: on

- remote_api: on

handlers:
- url: /static
  static_dir: static
  
- url: /static/image
  static_dir: static/image

- url: /static/js
  static_dir: static/js
    
- url: /.*
  script: SE2.main.application
